apiVersion: v1
kind: Service
metadata:
  name:  trozen-rtp-service
  namespace: trozen
spec:
  type: NodePort
  selector:
    app: trozen-rtp
  ports:
  - nodePort: 30082
    port: 80
    targetPort: 80